In [1]:
""" JS Comment
The following TF example could be treated as an implementation for 
"A Simple Machine Learning Example" as described at 
https://www.toptal.com/machine-learning/machine-learning-theory-an-introductory-primer
"""

' JS Comment\nThe following TF example could be treated as an implementation for \n"A Simple Machine Learning Example" as described at \nhttps://www.toptal.com/machine-learning/machine-learning-theory-an-introductory-primer\n'

In [2]:
import tensorflow as tf
import numpy as np

# Create 100 phony x, y data points in NumPy, y = x * 0.1 + 0.3
x_data = np.random.rand(100).astype(np.float32)
y_data = x_data * 0.1 + 0.3

# Try to find values for W and b that compute y_data = W * x_data + b
# (We know that W should be 0.1 and b 0.3, but TensorFlow will
# figure that out for us.)
W = tf.Variable(tf.random_uniform([1], -1.0, 1.0))
b = tf.Variable(tf.zeros([1]))
y = W * x_data + b

# Minimize the mean squared errors.
loss = tf.reduce_mean(tf.square(y - y_data))
optimizer = tf.train.GradientDescentOptimizer(0.5)
train = optimizer.minimize(loss)

# Before starting, initialize the variables.  We will 'run' this first.
init = tf.global_variables_initializer()

# Launch the graph.
sess = tf.Session()
sess.run(init)

# Fit the line.
for step in range(201):
    sess.run(train)
    if step % 20 == 0:
        print(step, sess.run(W), sess.run(b))

# Learns best fit is W: [0.1], b: [0.3]

AttributeError: 'module' object has no attribute 'global_variables_initializer'

In [3]:
init = tf.global_variables_initializer()

AttributeError: 'module' object has no attribute 'global_variables_initializer'

In [4]:
# JS Comment
# Correct global_variables_initializer to be initialize_all_variables
init = tf.initialize_all_variables()

In [5]:
# Launch the graph.
sess = tf.Session()
sess.run(init)

# Fit the line.
for step in range(201):
    sess.run(train)
    if step % 20 == 0:
        print(step, sess.run(W), sess.run(b))

# Learns best fit is W: [0.1], b: [0.3]

(0, array([ 0.73300499], dtype=float32), array([-0.05474651], dtype=float32))
(20, array([ 0.27341852], dtype=float32), array([ 0.20844421], dtype=float32))
(40, array([ 0.14688142], dtype=float32), array([ 0.27524912], dtype=float32))
(60, array([ 0.11267376], dtype=float32), array([ 0.29330894], dtype=float32))
(80, array([ 0.10342619], dtype=float32), array([ 0.29819116], dtype=float32))
(100, array([ 0.10092623], dtype=float32), array([ 0.29951102], dtype=float32))
(120, array([ 0.10025039], dtype=float32), array([ 0.29986781], dtype=float32))
(140, array([ 0.10006768], dtype=float32), array([ 0.29996428], dtype=float32))
(160, array([ 0.10001829], dtype=float32), array([ 0.29999036], dtype=float32))
(180, array([ 0.10000496], dtype=float32), array([ 0.29999739], dtype=float32))
(200, array([ 0.10000134], dtype=float32), array([ 0.2999993], dtype=float32))


In [6]:
""" JS Comment
Following is the illustration of np.random.rand
numpy.random.rand(d0, d1, ..., dn)
Random values in a given shape.

Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

Parameters:	
d0, d1, ..., dn : int, optional
The dimensions of the returned array, should all be positive. If no argument is given a single Python float is returned.
Returns:	
out : ndarray, shape (d0, d1, ..., dn)
Random values.
"""

' JS Comment\nFollowing is the illustration of np.random.rand\nnumpy.random.rand(d0, d1, ..., dn)\nRandom values in a given shape.\n\nCreate an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).\n\nParameters:\t\nd0, d1, ..., dn : int, optional\nThe dimensions of the returned array, should all be positive. If no argument is given a single Python float is returned.\nReturns:\t\nout : ndarray, shape (d0, d1, ..., dn)\nRandom values.\n'

In [7]:
np.random.rand(3,2)

array([[ 0.33234441,  0.81207218],
       [ 0.03815916,  0.92770422],
       [ 0.99123458,  0.77598703]])

In [8]:
np.random.rand(3,2,2)

array([[[ 0.34196052,  0.57871219],
        [ 0.21958943,  0.48992711]],

       [[ 0.21646525,  0.29631346],
        [ 0.67195522,  0.61265423]],

       [[ 0.59020432,  0.20342817],
        [ 0.60400803,  0.14083124]]])

In [9]:
np.random.rand(3,2,2,2)

array([[[[ 0.74498977,  0.73802347],
         [ 0.98020688,  0.30524357]],

        [[ 0.59478247,  0.6744565 ],
         [ 0.71159605,  0.35392092]]],


       [[[ 0.34706725,  0.90744536],
         [ 0.2242176 ,  0.87217952]],

        [[ 0.73906819,  0.56942867],
         [ 0.48293513,  0.94307421]]],


       [[[ 0.66528267,  0.30219423],
         [ 0.97178563,  0.24179359]],

        [[ 0.23953549,  0.50287948],
         [ 0.24358882,  0.24101976]]]])